# Generated by Django 4.2.11 on 2024-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinimage',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
