# Generated by Django 4.2.11 on 2024-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
