# Generated by Django 4.2.11 on 2024-06-19 22:40

from django.db import migrations, models
import skin_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_images', '0002_skinimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9999)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to=skin_images.models.user_directory_path)),
            ],
        ),
    ]
